version: "3.2"
services:
  gremlin:
    build:
      context: .
      dockerfile: Dockerfile-gremlin
      
    ports:
      - 8182:8182

  gremlex:
    build:
      context: ../
      dockerfile: Dockerfile
    entrypoint: ./docker-compose/test-entrypoint.sh
    environment:
      - GREMLEX_HOST=gremlin
    depends_on:
      - gremlin
    volumes:
      - ../:/app
